CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    UserName NVARCHAR(256) NOT NULL,
    Email NVARCHAR(256) NOT NULL,
    PasswordHash NVARCHAR(MAX) NULL
);

CREATE TABLE Books (
    BookId INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Author NVARCHAR(100) NULL,
    Genre NVARCHAR(50) NULL,
    ISBN NVARCHAR(20) NOT NULL,
    Available BIT NOT NULL,
    UserId NVARCHAR(450) NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
